builders:
  versionBuilder:
    import: "package:scip_dart/src/package_version/builder.dart"
    builder_factories: ["packageVersionBuilderFactory"]
    build_extensions: {'pubspec.yaml': ['lib/src/package_version/version.g.dart']}
    build_to: source
    auto_apply: root_package