name: scip_dart
version: 1.1.2
description: generates scip bindings for dart files
repository: https://github.com/Workiva/scip-dart

environment:
  sdk: ">=3.0.0 <4.0.0"

executables:
  scip_dart:

dependencies:
  analyzer: ^6.0.0
  args: ^2.4.0
  package_config: ^2.1.0
  path: ^1.8.3
  protobuf: ^2.1.0
  pubspec_parse: ^1.2.1

dev_dependencies:
  dependency_validator: ^3.2.2
  glob: ^2.1.1
  workiva_analysis_options: ^1.0.0