name: scip_dart
version: 1.2.2
description: generates scip bindings for dart files
repository: https://github.com/Workiva/scip-dart

environment:
  sdk: ">=2.18.0 <3.0.0"

executables:
  scip_dart:

dependencies:
  analyzer: ^5.4.0
  args: ^2.4.0
  package_config: ^2.1.0
  path: ^1.8.3
  protobuf: ^3.1.0
  pubspec_parse: ^1.2.1

dev_dependencies:
  chalk: ^1.2.1
  dart_dev: ^4.1.0
  dependency_validator: ^3.2.3
  glob: ^2.1.1
  workiva_analysis_options: ^1.4.1