import 'package:build/build.dart';
import 'package:pubspec_parse/pubspec_parse.dart';

// The directory that is written to
const _outputPath = 'lib/src/package_version/version.g.dart';

Builder packageVersionBuilderFactory(BuilderOptions options) => PackageVersionBuilder();

/// A really simple [Builder], it just makes copies of .txt files!
class PackageVersionBuilder implements Builder {
  @override
  final buildExtensions = const {
    'pubspec.yaml': [_outputPath]
  };

  @override
  Future<void> build(BuildStep buildStep) async {
    final inputId = buildStep.inputId;

    final pubspecYaml = await buildStep.readAsString(inputId);
    final version = Pubspec.parse(pubspecYaml).version;

    await buildStep.writeAsString(
      AssetId('scip_dart', _outputPath),
      '''// GENERATED BY package:scip-dart/src/package_version/builder.dart do not modify.

/// The current version of scip_dart
const packageVersion = '${version.toString()}';''',
    );
  }
}