import 'package:build/build.dart';
import 'package:pubspec_parse/pubspec_parse.dart';
import 'package:scip_dart/src/utils.dart';

Builder versionBuilderFactory(BuilderOptions options) => VersionBuilder();

/// A really simple [Builder], it just makes copies of .txt files!
class VersionBuilder implements Builder {
  @override
  final buildExtensions = const {
    'pubspec.yaml': ['lib/src/version/version.g.dart']
  };

  @override
  Future<void> build(BuildStep buildStep) async {
    final inputId = buildStep.inputId;

    final pubspecYaml = await buildStep.readAsString(inputId);
    final version = Pubspec.parse(pubspecYaml).version;

    await buildStep.writeAsString(
      AssetId('scip_dart', 'lib/src/version/version.g.dart'),
      '''
      // GENERATED BY package:scip-dart/src/version/version_builder.dart do not modify.

      /// The current version of scip_dart
      const scipDartVersion = '${version.toString()}';
      '''.trimIndent(),
    );
  }
}