name: Checks

on:
  pull_request:

jobs:
  format:
    runs-on: workiva-runner-dev
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - run: dart pub get
      - run: dart run dart_dev format

  dependency-validator:
    runs-on: workiva-runner-dev
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: stable
      - run: dart pub get
      - run: dart run dependency_validator