name: Tests

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  pull-requests: write
  contents: write
  id-token: write

jobs:
  checks:
    uses: Workiva/gha-dart-oss/.github/workflows/checks.yaml@v0.1.0

  sbom:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.19.6
      - uses: anchore/sbom-action@v0
        with:
          path: ./
          format: cyclonedx-json

  snapshots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install scip cli
        run: |
          bash -c 'curl -L "https://github.com/sourcegraph/scip/releases/download/v0.3.3/scip-linux-amd64.tar.gz"' | tar xzf - scip
          ./scip --version

      - uses: dart-lang/setup-dart@v1
        with:
          # use a fixed version number so changes to 'stable', dont break snapshot diffs (language version is used in the scip symbol)
          sdk: 2.19.6
      - name: dart pub get scip-dart package
        run: dart pub get

      - name: dart pub get basic-project directory
        run: dart pub get
        working-directory: ./snapshots/input/basic-project

      - name: dart pub get diagnostics directory
        run: dart pub get
        working-directory: ./snapshots/input/diagnostics

      - name: Snapshots Diff Check
        run: |
          dart run scip_dart ./snapshots/input/basic-project
          ./scip snapshot --to ./snapshots/output/basic-project

          dart run scip_dart ./snapshots/input/diagnostics
          ./scip snapshot --to ./snapshots/output/diagnostics

          if [[ -z "$(git status --porcelain ./snapshots/output)" ]];
          then
            echo "No changes to snapshot files"
          else
            echo
            echo "Snapshot diff detected differences, run 'make gen-snaps' to re-generate snapshots"
            git status --short ./snapshots/output
            echo
            exit 1
          fi

  consumer:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        consumer: [
          { repo: "Workiva/over_react" },
          { repo: "Workiva/w_module" },
          { repo: "rrousselGit/provider", packagePath: "/packages/provider" },
          { repo: "dart-lang/args", ref: "v2.4.2" } # master requires dart 3
        ]

    steps:
      # Setup scip-dart
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.19.6
      - working-directory: ${{ matrix.consumer.packagePath || './' }}
        run: dart pub get

      # Setup repo to run on
      - uses: actions/checkout@v4
        with:
          repository: ${{ matrix.consumer.repo }}
          path: ${{ matrix.consumer.repo}}
          ref: ${{ matrix.consumer.ref || 'master' }}
      - run: dart pub get
        working-directory: ${{ matrix.consumer.repo }}

      - run: |
          dart run scip_dart ./${{ matrix.consumer.repo }}${{ matrix.consumer.packagePath || '' }} || exit 1
