name: Scip

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read
  id-token: write

jobs:
  index:
    runs-on: workiva-runner-dev
    steps:
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.18.7

      - run: dart pub get

      # - run: dart pub global activate --hosted-url https://pub.workiva.org scip_dart
      - run: dart pub global activate -spath .


      - name: scip index
        run: dart pub global run scip_dart ./

      # provides SRC_ENDPOINT and SRC_ACCESS_TOKEN to the src installation step
      - uses: Workiva/gha-setup-credentials@v1.0.0
        with:
          vault-url: https://vault-dev.workiva.org
          vault-env: dev

      # Install src cli
      - name: Install Sourcegraph CLI
        run: |
          curl -L https://sourcegraph.com/.api/src-cli/src_linux_amd64 -o _src-cli
          chmod +x _src-cli
          ./_src-cli login
          echo ./_src-cli endpoint $SRC_ENDPOINT
          echo ./_src-cli access token $SRC_ACCESS_TOKEN
      
      - name: Upload scip to sourcegraph
        run: ./_src-cli code-intel upload -file=index.scip -github-token="${{ env.FEF_GH_TOKEN }}"