name: Setup Dart
description: A single location to setup dart so all versions are consistent in CI

runs:
  using: composite
  steps:
    - uses: dart-lang/setup-dart@v1
      with:
        # use a fixed version number so changes to 'stable', dont break snapshot diffs (language version is used in the scip symbol)
        sdk: 2.18.7