name: Tests

on:
  push:
    branches:
      - master
  pull_request:


jobs:
  snapshots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install scip cli
        run: |
          bash -c 'curl -L "https://github.com/sourcegraph/scip/releases/download/v0.2.3/scip-linux-amd64.tar.gz"' | tar xzf - scip
          ./scip --version

      - uses: dart-lang/setup-dart@v1
        with:
          # use a fixed version number so changes to 'stable', dont break snapshot diffs (language version is used in the scip symbol)
          sdk: 2.18.7
      - name: pub get scip-dart package
        run: dart pub get

      - name: pub get snapshots directory
        run: dart pub get
        working-directory: ./snapshots/input/basic-project

      - name: Snapshots Diff Check
        run: |
          dart run scip_dart ./snapshots/input/basic-project
          ./scip snapshot --to ./snapshots/output/basic-project

          if [[ -z "$(git status --porcelain ./snapshots/output)" ]];
          then
            echo "No changes to snapshot files"
          else
            echo
            echo "Snapshot diff detected differences, run 'make run snap' to re-generate snapshots"
            git status --short ./snapshots/output
            echo
            exit 1
          fi

  consumer:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        repo: [
          "Workiva/over_react",
          "Workiva/w_module",
          "rrousselGit/provider",
          "dart-lang/args",
        ]

    steps:
      # Setup scip-dart
      - uses: actions/checkout@v3
      - uses: dart-lang/setup-dart@v1
        with:
          sdk: 2.18.7
      - run: dart pub get

      # Setup repo to run on
      - uses: actions/checkout@v3
        with:
          repo: ${{ matrix.repo }}
          path: ${{ matrix.repo }}
      - run: dart pub get
        working-directory: ${{ matrix.repo }}

      - run: |
          dart run scip_dart ./${{ matrix.repo }} || exit 1
